name: Email VC Issuer deploy to prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          cd front
          yarn
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MAIN_AWS_REGION }}

      - name: Deploy site to S3
        run: |
          cd front
          aws s3 sync --delete --only-show-errors build/ ${{ secrets.MAIN_S3_BUCKET }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.MAIN_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
